// Mock for lucide-react icons
const React = require("react");

const createMockIcon = (displayName) => {
  const Component = React.forwardRef((props, ref) =>
    React.createElement("svg", {
      "data-testid": `${displayName.toLowerCase()}-icon`,
      ref,
      ...props,
    })
  );
  Component.displayName = displayName;
  return Component;
};

module.exports = {
  __esModule: true,
  Menu: createMockIcon("Menu"),
  X: createMockIcon("X"),
  Moon: createMockIcon("Moon"),
  Sun: createMockIcon("Sun"),
  Send: createMockIcon("Send"),
  Mail: createMockIcon("Mail"),
  Phone: createMockIcon("Phone"),
  Github: createMockIcon("Github"),
  Linkedin: createMockIcon("Linkedin"),
  Twitter: createMockIcon("Twitter"),
  ExternalLink: createMockIcon("ExternalLink"),
  Upload: createMockIcon("Upload"),
  Loader2: createMockIcon("Loader2"),
  ZoomIn: createMockIcon("ZoomIn"),
  ZoomOut: createMockIcon("ZoomOut"),
  Calendar: createMockIcon("Calendar"),
  Clock: createMockIcon("Clock"),
  MapPin: createMockIcon("MapPin"),
  Building: createMockIcon("Building"),
  GraduationCap: createMockIcon("GraduationCap"),
  Award: createMockIcon("Award"),
  Code: createMockIcon("Code"),
  FileText: createMockIcon("FileText"),
  Tag: createMockIcon("Tag"),
  Briefcase: createMockIcon("Briefcase"),
  Users: createMockIcon("Users"),
  Star: createMockIcon("Star"),
  Download: createMockIcon("Download"),
  Eye: createMockIcon("Eye"),
  Heart: createMockIcon("Heart"),
  MessageCircle: createMockIcon("MessageCircle"),
  Share2: createMockIcon("Share2"),
  ArrowRight: createMockIcon("ArrowRight"),
  ChevronRight: createMockIcon("ChevronRight"),
  ChevronLeft: createMockIcon("ChevronLeft"),
  Search: createMockIcon("Search"),
  Filter: createMockIcon("Filter"),
  Plus: createMockIcon("Plus"),
  Minus: createMockIcon("Minus"),
  Edit: createMockIcon("Edit"),
  Trash: createMockIcon("Trash"),
  Check: createMockIcon("Check"),
  AlertCircle: createMockIcon("AlertCircle"),
  Info: createMockIcon("Info"),
  Settings: createMockIcon("Settings"),
  LogOut: createMockIcon("LogOut"),
  Image: createMockIcon("Image"),
  Folder: createMockIcon("Folder"),
  File: createMockIcon("File"),
  User: createMockIcon("User"),
  Globe: createMockIcon("Globe"),
  ArrowLeft: createMockIcon("ArrowLeft"),
  Video: createMockIcon("Video"),
  BookOpen: createMockIcon("BookOpen"),
  EyeOff: createMockIcon("EyeOff"),
  Loader: createMockIcon("Loader"),
  Crop: createMockIcon("Crop"),
  ChevronDown: createMockIcon("ChevronDown"),
  ChevronUp: createMockIcon("ChevronUp"),
  MoreVertical: createMockIcon("MoreVertical"),
  CheckCircle2: createMockIcon("CheckCircle2"),
  XCircle: createMockIcon("XCircle"),
};
